# Generated by Django 4.1.2 on 2022-10-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "experiences",
            "0003_alter_experience_category_alter_experience_host_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="perk",
            old_name="detail",
            new_name="details",
        ),
    ]
