# Generated by Django 4.1.2 on 2023-06-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0007_alter_amenity_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="icon_image",
            field=models.TextField(null=True),
        ),
    ]
