# Generated by Django 4.1.2 on 2023-07-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0003_alter_photo_file_alter_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
